name: Check Zitplaatsen Mismatch

on:
  workflow_dispatch: # Hiermee kun je het script handmatig starten

jobs:
  check-seats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run check seats
        env:
          DISCORD_WEBHOOK_URL_ZITPLAATSEN: ${{ secrets.DISCORD_WEBHOOK_URL_ZITPLAATSEN }}
        run: python extra_scripts/bezetting.py
