name: Run hulpdienstvoertuigenbenelux Script

on:
  workflow_dispatch:     # <-- Voeg deze regel toe om handmatig te kunnen starten!

concurrency:
  group: production-deploy
  cancel-in-progress: false
  queue: max
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Amsterdam
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        env:
          DISCORD_WEBHOOK_URL_NL: ${{ secrets.DISCORD_WEBHOOK_URL_NL }}
          DISCORD_WEBHOOK_URL_BE: ${{ secrets.DISCORD_WEBHOOK_URL_BE }}
          DISCORD_WEBHOOK_URL_LUX: ${{ secrets.DISCORD_WEBHOOK_URL_LUX }}
          DISCORD_WEBHOOK_URL_DE: ${{ secrets.DISCORD_WEBHOOK_URL_DE }}
          DISCORD_APK: ${{ secrets.DISCORD_APK }}
          RDW_API_CHANGES_WEBHOOK: ${{ secrets.RDW_API_CHANGES_WEBHOOK }}
          RDW_APP_TOKEN: ${{ secrets.RDW_APP_TOKEN }}
          HVNBL_RDW_API_KEY: ${{ secrets.HVNBL_RDW_API_KEY }}
          DISCORD_WEBHOOK_URL_RDW_API_PUSH: ${{ secrets.DISCORD_WEBHOOK_URL_RDW_API_PUSH }}
        run: |
          git pull
          python compare_hulpdienstvoertuigenbenelux.py ALL
          python rdw_checker.py
          python extra_scripts/poll_inrichting.py
          python check_duplicates.py
          python fetch_rdw_subdata.py
          python combine_data.py
          python extra_scripts/combine_rdw_subdata.py
          python extra_scripts/rdw_push.py
          python validate_regions.py

      - name: Commit and push changes
        run: |
          git add .
          git diff --cached --quiet || (git commit -m "Automated update from GitHub Actions" && git push)
