name: Run RDW Push Script

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Amsterdam
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run rdw_push
        env:
          HVNBL_RDW_API_KEY: ${{ secrets.HVNBL_RDW_API_KEY }}
          DISCORD_WEBHOOK_URL_RDW_API_PUSH: ${{ secrets.DISCORD_WEBHOOK_URL_RDW_API_PUSH }}
        run: |
          python extra_scripts/combine_rdw_subdata.py
          python extra_scripts/rdw_push.py
